interfaces:
  - name: 1
    ip: 10.3.255.106
    mask: 255.255.255.0
    loopback: false
    ospf: area 0
  - name: 0
    ip: 6.6.6.6
    mask: 255.255.255.255
    loopback: true
    ospf: area 0
  - name: 1
    ip: 192.168.6.1
    mask: 255.255.255.0
    loopback: false
    ospf: area 0

ospf: 
  - process_id: 6
  - router_id: 6.6.6.6
  - area: 0

bgp:
  - as_number: 6
  - multihop_count: 2
  - source_update: lo0



